export const getSkillInfo = (skillName) => {
  const skillMap = {
    // 프로그래밍 언어 (파란색 계열)
    JavaScript: { color: "bg-blue-300", iconPath: "/icon/JavaScript.svg" },
    TypeScript: { color: "bg-blue-300", iconPath: "/icon/TypeScript.svg" },
    Java: { color: "bg-blue-300", iconPath: "/icon/Java-Dark.svg" },
    PHP: { color: "bg-blue-300", iconPath: "/icon/PHP-Dark.svg" },
    Python: { color: "bg-blue-300", iconPath: "/icon/Python-Dark.svg" },
    C: { color: "bg-blue-300", iconPath: "/icon/C.svg" },
    "C++": { color: "bg-blue-300", iconPath: "/icon/CPP.svg" },
    "C#": { color: "bg-blue-300", iconPath: "/icon/CS.svg" },
    Go: { color: "bg-blue-300", iconPath: "/icon/GoLang.svg" },
    Rust: { color: "bg-blue-300", iconPath: "/icon/Rust.svg" },
    Ruby: { color: "bg-blue-300", iconPath: "/icon/Ruby.svg" },
    Swift: { color: "bg-blue-300", iconPath: "/icon/Swift.svg" },
    Kotlin: { color: "bg-blue-300", iconPath: "/icon/Kotlin-Dark.svg" },
    Dart: { color: "bg-blue-300", iconPath: "/icon/Dart-Dark.svg" },

    // 백엔드 프레임워크/런타임 (녹색 계열)
    "Node.js": { color: "bg-green-300", iconPath: "/icon/NodeJS-Dark.svg" },
    SpringBoot: { color: "bg-green-300", iconPath: "/icon/Spring-Dark.svg" },
    "Java/Spring Boot": { color: "bg-green-300", iconPath: "/icon/Spring-Dark.svg" },
    JPA: { color: "bg-green-300", iconPath: "/icon/Hibernate-Dark.svg" },
    Mybatis: { color: "bg-green-300", iconPath: "/icon/Mybatis.png" },
    JSP: { color: "bg-green-300", iconPath: "/icon/JSP.png" },
    "Spring Cloud": { color: "bg-green-300", iconPath: "/icon/Spring-Dark.svg" },
    "Spring Security": { color: "bg-green-300", iconPath: "/icon/Spring-Dark.svg" },
    Express: { color: "bg-green-300", iconPath: "/icon/ExpressJS-Dark.svg" },
    "Express.js": { color: "bg-green-300", iconPath: "/icon/ExpressJS-Dark.svg" },
    NestJS: { color: "bg-green-300", iconPath: "/icon/NestJS-Dark.svg" },
    Django: { color: "bg-green-300", iconPath: "/icon/Django.svg" },
    Flask: { color: "bg-green-300", iconPath: "/icon/Flask-Dark.svg" },
    FastAPI: { color: "bg-green-300", iconPath: "/icon/FastAPI.svg" },
    Rails: { color: "bg-green-300", iconPath: "/icon/Rails.svg" },
    Laravel: { color: "bg-green-300", iconPath: "/icon/Laravel-Dark.svg" },
    Symfony: { color: "bg-green-300", iconPath: "/icon/Symfony-Dark.svg" },
    "Socket.io": { color: "bg-green-300", iconPath: "/icon/Socket.io.svg" },

    // 프론트엔드 마크업/스타일링 (보라색 계열)
    HTML5: { color: "bg-purple-300", iconPath: "/icon/HTML.svg" },
    HTML: { color: "bg-purple-300", iconPath: "/icon/HTML.svg" },
    CSS: { color: "bg-purple-300", iconPath: "/icon/CSS.svg" },
    Sass: { color: "bg-purple-300", iconPath: "/icon/Sass.svg" },
    "Tailwind CSS": { color: "bg-purple-300", iconPath: "/icon/TailwindCSS-Dark.svg" },
    Tailwind: { color: "bg-purple-300", iconPath: "/icon/TailwindCSS-Dark.svg" },
    Bootstrap: { color: "bg-purple-300", iconPath: "/icon/Bootstrap.svg" },
    "Material UI": { color: "bg-purple-300", iconPath: "/icon/MaterialUI-Dark.svg" },
    "Styled Components": { color: "bg-purple-300", iconPath: "/icon/StyledComponents.svg" },

    // 프론트엔드 프레임워크/라이브러리 (분홍색 계열)
    React: { color: "bg-pink-300", iconPath: "/icon/React-Dark.svg" },
    "Next.js": { color: "bg-pink-300", iconPath: "/icon/NextJS-Dark.svg" },
    NextJS: { color: "bg-pink-300", iconPath: "/icon/NextJS-Dark.svg" },
    Vue: { color: "bg-pink-300", iconPath: "/icon/Vue.svg" },
    "Vue.js": { color: "bg-pink-300", iconPath: "/icon/VueJS-Dark.svg" },
    Angular: { color: "bg-pink-300", iconPath: "/icon/Angular-Dark.svg" },
    Svelte: { color: "bg-pink-300", iconPath: "/icon/Svelte.svg" },
    Nuxt: { color: "bg-pink-300", iconPath: "/icon/NuxtJS-Dark.svg" },
    Gatsby: { color: "bg-pink-300", iconPath: "/icon/Gatsby.svg" },
    Remix: { color: "bg-pink-300", iconPath: "/icon/Remix-Dark.svg" },
    jQuery: { color: "bg-pink-300", iconPath: "/icon/JQuery.svg" },
    "Framer Motion": { color: "bg-pink-300", iconPath: "/icon/Framer-Motion.svg" },
    "Chart.js": { color: "bg-pink-300", iconPath: "/icon/Chart.js.svg" },
    "React DnD": { color: "bg-pink-300", iconPath: "/icon/React-Dark.svg" },
    "Three.js": { color: "bg-pink-300", iconPath: "/icon/ThreeJS-Dark.svg" },
    D3: { color: "bg-pink-300", iconPath: "/icon/D3-Dark.svg" },
    Redux: { color: "bg-pink-300", iconPath: "/icon/Redux.svg" },
    "React Native": { color: "bg-pink-300", iconPath: "/icon/React-Dark.svg" },
    Flutter: { color: "bg-pink-300", iconPath: "/icon/Flutter-Dark.svg" },
    Electron: { color: "bg-pink-300", iconPath: "/icon/Electron.svg" },

    // 데이터베이스 (주황색 계열)
    MySQL: { color: "bg-orange-300", iconPath: "/icon/MySQL-Dark.svg" },
    MongoDB: { color: "bg-orange-300", iconPath: "/icon/MongoDB.svg" },
    PostgreSQL: { color: "bg-orange-300", iconPath: "/icon/PostgreSQL-Dark.svg" },
    SQLite: { color: "bg-orange-300", iconPath: "/icon/SQLite.svg" },
    Redis: { color: "bg-orange-300", iconPath: "/icon/Redis-Dark.svg" },
    Cassandra: { color: "bg-orange-300", iconPath: "/icon/Cassandra-Dark.svg" },
    DynamoDB: { color: "bg-orange-300", iconPath: "/icon/DynamoDB-Dark.svg" },
    Prisma: { color: "bg-orange-300", iconPath: "/icon/Prisma.svg" },
    Sequelize: { color: "bg-orange-300", iconPath: "/icon/Sequelize-Dark.svg" },

    // DevOps & 인프라 (청록색 계열)
    Git: { color: "bg-cyan-300", iconPath: "/icon/Git.svg" },
    GitHub: { color: "bg-cyan-300", iconPath: "/icon/Github-Dark.svg" },
    "GitHub Actions": { color: "bg-cyan-300", iconPath: "/icon/GithubActions-Dark.svg" },
    GitLab: { color: "bg-cyan-300", iconPath: "/icon/GitLab-Dark.svg" },
    Docker: { color: "bg-cyan-300", iconPath: "/icon/Docker.svg" },
    Jenkins: { color: "bg-cyan-300", iconPath: "/icon/Jenkins-Dark.svg" },
    Kubernetes: { color: "bg-cyan-300", iconPath: "/icon/Kubernetes.svg" },
    K8s: { color: "bg-cyan-300", iconPath: "/icon/Kubernetes.svg" },
    Linux: { color: "bg-cyan-300", iconPath: "/icon/Linux-Dark.svg" },
    Ubuntu: { color: "bg-cyan-300", iconPath: "/icon/Ubuntu.png" },
    ArgoCD: { color: "bg-cyan-300", iconPath: "/icon/ArgoCD.png" },
    AWS: { color: "bg-cyan-300", iconPath: "/icon/AWS-Dark.svg" },
    Azure: { color: "bg-cyan-300", iconPath: "/icon/Azure-Dark.svg" },
    GCP: { color: "bg-cyan-300", iconPath: "/icon/GCP-Dark.svg" },
    Vercel: { color: "bg-cyan-300", iconPath: "/icon/Vercel-Dark.svg" },
    Netlify: { color: "bg-cyan-300", iconPath: "/icon/Netlify-Dark.svg" },
    Heroku: { color: "bg-cyan-300", iconPath: "/icon/Heroku.svg" },
    Nginx: { color: "bg-cyan-300", iconPath: "/icon/Nginx.svg" },
    Terraform: { color: "bg-cyan-300", iconPath: "/icon/Terraform.svg" },
    Ansible: { color: "bg-cyan-300", iconPath: "/icon/Ansible.svg" },

    // 기타 도구들
    Firebase: { color: "bg-gray-300", iconPath: "/icon/Firebase-Dark.svg" },
    Supabase: { color: "bg-gray-300", iconPath: "/icon/Supabase-Dark.svg" },
    GraphQL: { color: "bg-gray-300", iconPath: "/icon/GraphQL-Dark.svg" },
    Apollo: { color: "bg-gray-300", iconPath: "/icon/Apollo.svg" },
    Webpack: { color: "bg-gray-300", iconPath: "/icon/Webpack-Dark.svg" },
    Vite: { color: "bg-gray-300", iconPath: "/icon/Vite-Dark.svg" },
    Rollup: { color: "bg-gray-300", iconPath: "/icon/RollupJS-Dark.svg" },
    Babel: { color: "bg-gray-300", iconPath: "/icon/Babel.svg" },
    Jest: { color: "bg-gray-300", iconPath: "/icon/Jest.svg" },
    Cypress: { color: "bg-gray-300", iconPath: "/icon/Cypress.svg" },
    Selenium: { color: "bg-gray-300", iconPath: "/icon/Selenium.svg" },
    Postman: { color: "bg-gray-300", iconPath: "/icon/Postman.svg" },
    Figma: { color: "bg-gray-300", iconPath: "/icon/Figma-Dark.svg" },
    "VS Code": { color: "bg-gray-300", iconPath: "/icon/VSCode.svg" },
    VSCode: { color: "bg-gray-300", iconPath: "/icon/VSCode.svg" },
    IntelliJ: { color: "bg-gray-300", iconPath: "/icon/Idea-Dark.svg" },
    AndroidStudio: { color: "bg-gray-300", iconPath: "/icon/AndroidStudio-Dark.svg" },
    Xcode: { color: "bg-gray-300", iconPath: "/icon/Xcode.svg" },
    Expo: { color: "bg-gray-300", iconPath: "/icon/Expo.svg" },
    MDX: { color: "bg-gray-300", iconPath: "/icon/MDX.svg" },
    "Weather API": { color: "bg-gray-300", iconPath: "/icon/API.svg" },
  };

  return skillMap[skillName] || { color: "bg-gray-300", iconPath: "/icon/Code.svg" };
};
