import "./globals.css";

export const metadata = {
  title: "hoya",
  description: "Generated by Readdy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning={true}>
      <body className="font-[pretendard]">{children}</body>
    </html>
  );
}
